name: Semver Check

on:
  pull_request:
    types: [opened, synchronize, reopened, edited, ready_for_review]

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: reattach HEAD to Head Ref
      run: git checkout "$(echo ${{ github.head_ref }} | sed -E 's|refs/[a-zA-Z]+/||')"
      if: github.head_ref != ''
    # - name: Prepare repository
    #   run: git pull origin waqas_gh_action
    # - name: reattach HEAD to Ref
    #   run: git checkout "$(echo ${{ github.ref }} | sed -E 's|refs/[a-zA-Z]+/||')"
    #   if: github.head_ref == ''
    - name: Check Semver in PR Title and Commit Message
      id: pr
      run: |
        echo "This is workflow"
       
